services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
  server:
    build: ./server
    command: bun dev
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/teste
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    command: bun dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  db_data: